// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SolarSoft_1._0.Context;

#nullable disable

namespace SolarSoft_1._0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240319114414_InicializacionDb")]
    partial class InicializacionDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolarSoft_1._0.Models.Panel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<double>("ANCHOPANEL")
                        .HasColumnType("float");

                    b.Property<double>("ANCHOTERRENO")
                        .HasColumnType("float");

                    b.Property<int>("ANGULOESTRUCTURA")
                        .HasColumnType("int");

                    b.Property<double>("LARGOTERRENO")
                        .HasColumnType("float");

                    b.Property<double>("LATITUD")
                        .HasColumnType("float");

                    b.Property<double>("LONGITUD")
                        .HasColumnType("float");

                    b.Property<double>("LONGITUDPANEL")
                        .HasColumnType("float");

                    b.Property<int>("POTENCIA")
                        .HasColumnType("int");

                    b.Property<double>("VOLTAJE")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Paneles");
                });
#pragma warning restore 612, 618
        }
    }
}
